### PR TITLE
Repository Overhaul

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
Please check the **[Preview]**.

<br>

*What will the adjust colors script do in the end?*
( details , one time thing or used repeatedly )

<br>

### Changes

- Moved icons into Icons folder

  *Tidies up root folder / repo*

  *Makes creating releases easier*

- Added donate , license badges

- General formatting / spacing

- Put preview in Resources folder

  *Adjusted paths*

<br>

### Repository Suggetions

- Add description

- Use the `Releases` function to package icons

- Disable unused tabs:

  - `Actions`

- Use the `Projects` tab for icon conversion / addition progress

- Add sponsoring methods that can be shown
  with Githubs sponsor function

  https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

[Preview]: https://github.com/ElectronicsArchiver/Evolvere-Icons

### CODE REVIEW

**Comment by franksouza183** [comment]
Wonderful work, thank you! I will have to change little things like the paypal button as my account doesn't support donation buttons. I'll be looking at the github sponsors suggestion, but I intend to go for some alternative in cryptocurrencies in parallel to paypal.
As for the script, it aims to replace, at first, small icons colors, useful if the user use dark themes in environments that do not support symbolic icons, such as xfce, lxde, etc. The script would then just apply transparent colors to the fallback contours, also, can be used to colorize foreground color to a user specified one or from the current gtk/qt theme. I haven't delved into this yet because I haven't finished converting all the small icons to the new style, using the default colors that will be replaced, I just did some tests and forgot the script there after seeing that it would be possible. I believe that there must be some tool that works directly with the DOM in XML file contents through shellscript, this would make it much easier to create more customized themes and could work directly with attributes of the elements instead of simple string replacements, nice if I want add/remove classes/id's inline css, etc.
Another purpose of the script is to create variants, but I will still test some ways to do this, mainly with the use of embedded SVG elements and their cross-environment compatibility, if it doesn't work as I expect, I'll have to use a similar way to the one used with the small icons.

**Comment by ElectronicsArchiver** [comment]
Thanks for the merge,
about the script, why not go for a lang like js / python
to make this into a more accessible tool?

Especially considering the SVG part seems much more
sensible to do in those langs as module for that already
exist.

If you wrote up a concept on how to select those icons
and what properties to make changeable I could write
up a small tool~

**Comment by franksouza183** [comment]
it would be wonderful, I can do that, but first I need to do some compatibility tests, as I mentioned, this will define part of the concept. I will try to look at this this weekend.

**Comment by ElectronicsArchiver** [comment]
I guess you didn't have time to look into it?

**Comment by franksouza183** [comment]
Sorry, the weekend took too long xD

The script should replace the color and alpha of certain elements containing specific classes (see below) with those specified by the user in monochrome icons only (should not be filtered by directories since some large monochrome icons exist). I think using templates would be interesting, pulling data from files located in a specific directory, and in principle, containing the options:
```
fgc: hex color, foregroung color, overrides ".ColorScheme-Text" css value, default: #090d11
fga: float, 0 to 1; foreground alpha, inline overrides (see bellow), default: .75
bgc: hex color or 'none', background color, overrides ".ColorScheme-Background" css value or inline if 'none' (see bellow), default: #ffffff
bga: float, 0 to 1; foreground alpha, inline overrides (see bellow), default: .5
ac: hex color, accent color, overrides ".ColorScheme-Highlight" css value, default: #2598e4
aca: float, 0 to 1; accent color alpha, inline overrides (see bellow), default: 1
wc: hex color, warning color, overrides ".ColorScheme-NeutralText" css value, default: #f2712c
wca: float, 0 to 1; foreground alpha, inline overrides (see bellow), default: 1
ec: error color, foregroung color, overrides ".ColorScheme-NegativeText" css value, default: #f03489
eca: float, 0 to 1; foreground alpha, inline overrides (see bellow), default: 1
sc: hex color, success color, overrides ".ColorScheme-PositiveText" css value, default: #42a53b
sca: float, 0 to 1; success alpha, inline overrides (see bellow), default: 1
```
The option that contains hex color should only replace the color in the <style> declaration in each svg file, not inline:

```
<defs>
    <style id="current-color-scheme" type="text/css">

        .ColorScheme-Text{color:#090d11;} <!-- fgc -->
        .ColorScheme-Background{color:#ffffff;} <!-- bgc -->
        .ColorScheme-Highlight{color:#2598e4;} <!-- ac -->
        .ColorScheme-NeutralText{color:#f2712c;} <!-- wc -->
        .ColorScheme-NegativeText {color:#f03489;} <!-- ec -->
        .ColorScheme-PositiveText {color:#42a53b;} <!-- sc -->

    </style>
</defs>
```

For the variables "bgc"="none" and related to alpha (fga, bga, wca...) it will be necessary to edit the style inline in the DOM element:

For the following configuration:

`template_X.ini`
```
bgc=none
bga=1
```

`example_icon.svg`
```
<path
    class="ColorScheme-Background"
    d="m2 1c-1.0907 0-2"
    style="fill-opacity:.5;fill:currentColor"
/>
```

turns into ...

`example_icon.svg`
```
<path
    class="ColorScheme-Background"
    d="m2 1c-1.0907 0-2"
    style="fill-opacity:1;fill:currentColor;opacity:0"
/>
```
For the following configuration:
`
template_Y.ini`
```
fgc=#0000ff
fga=1
```
`example_icon.svg`
```
<defs>
    <style id="current-color-scheme" type="text/css">
        ...
        .ColorScheme-Text{color:#090d11;} <!-- fgc -->
        ...
    </style>
</defs>
...
<path
    class="ColorScheme-Text"
    d="m2 1c-1.0907 0-2"
    style="fill-opacity:.75;fill:currentColor"
/>
```

turns into ...

`example_icon.svg`
```
<defs>
    <style id="current-color-scheme" type="text/css">
        ...
        .ColorScheme-Text{color:#0000ff;} <!-- fgc -->
        ...
    </style>
</defs>
...
<path
    class="ColorScheme-Text"
    d="m2 1c-1.0907 0-2"
    style="fill-opacity:1;fill:currentColor;"
/>
```
I believe that XML manipulation (XPath?) will be needed instead of just string replacement.

**Comment by ElectronicsArchiver** [comment]
Do the monochrome files have some sort of identifier or do I have to manually check for them?

> XPath

Don't worry, I already have a lib for that in mind~

**Comment by ElectronicsArchiver** [comment]
Oh and where do you want the colorized version to be put?
In a generated `Build` folder?

**Comment by franksouza183** [comment]
> Do the monochrome files have some sort of identifier or do I have to manually check for them?
No, the script must scan all svg files except symlinks. As for the destination directory, it is up to the user to create a new theme or replace the current one (current user or system-wide). If a new theme is created, the new index.theme file must contain the "Name" property with a different value.

**Comment by franksouza183** [comment]
> Sure, did you have any way of identifying them in mind?

It's not possible, the script should only search for the classes, there's no problem if affect larger icons, it should be concern for the icon designer. Also, it's good that affect them since some of them uses the accent/warning/error color, that's ok.

**Comment by franksouza183** [comment]
yes it is expected xD

**Comment by ElectronicsArchiver** [comment]
Btw, so the built theme should contain the `index.theme` file,
but should the symlink be present as well or are they only for
designing the icons?

Also isn't the `icon-theme.cache` a local file from 
your system that shouldn't be in the repository?

**Comment by franksouza183** [comment]
The built theme should be a copy of the main theme, replacing only the tweaked files and the index-theme.cache should be generated for the new theme with `gtk-update-icon-cache`

**Comment by ElectronicsArchiver** [comment]
The `Discussions` might come in handy to discuss stuff like this~

**Comment by franksouza183** [comment]
enabled

**Pull request merged**
