### PR TITLE
Documentation Extension

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
<br>

*Please check the* ***[Preview]***

<br>

### Changes

- Moved & formatted installation into dedicated file
- Linked installation in quicklinks
- Added issue template for icons

  *You probably want to modify it to your needs~*

[Preview]: https://github.com/franksouza183/Evolvere-Icons/tree/Documentation-1

### CODE REVIEW

**Comment by franksouza183** [comment]
I didn't understand this "You can call it from anywhere." part. You still need to specify the path of the script to launch it, unless you manually specify the path of the tool in the env var $PATH

**Comment by ElectronicsArchiver** [comment]
That in reference to the fact that many programs such as make, require you by default to be in a specific location, such as the project folder specifically, for colorize though, you can be in, idk, `~/` for example and call it with it's path and it would still find the icons folder.

**Comment by ElectronicsArchiver** [comment]
Let me modify it real quick~

**Comment by ElectronicsArchiver** [comment]
[Here you go](https://github.com/franksouza183/Evolvere-Icons/blob/Documentation-1/Documentation/Colorize/Usage.md)

**Comment by franksouza183** [comment]
I think is all good

**Pull request merged**
